export const STATE = {
  ORDER_WAITING: "ORDERING",
  ORDER_COMPLETE: "ORDER_COMPLETED",
  DELIVERY_COMPLETE: "DELIVERY_COMPLETE",
  REQ_WAITING: "AWAITING",
  ACCEPTED: "RECRUITING",
  DENIED: "REJECTED",
  CHIEF: 6,
};
